language: php
php:
  - 7.3
#sudo: required
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - bash setting.sh

script:
  #coding_convention:
  ./vendor/squizlabs/php_codesniffer/bin/phpcs --standard=PSR2 app/ routes/ config/
#script: ./vendor/bin/phpunit

notifications:
  email: false
#    - tunglt@ominext.com

branches:
  only:
    - master
