language: php
php:
  - 7.3
#sudo: required
cache:
  directories:
    - node_modules
    - vendor
before_script:
  - bash setting.sh

script:
  ./vendor/squizlabs/php_codesniffer/bin/phpcs --standard=PSR2 app/ routes/ config/ tests/ database/
#script: ./vendor/bin/phpunit

notifications:
  email: false
#notifications:
#  email:
#    - tunglt@ominext.com

#coding_convention:
#  script:
#    - vendor/squizlabs/php_codesniffer/bin/phpcs --standard=PSR2 app/ routes/ config/ tests/ database/
